// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB0Gn3T3lvP2Q-Rn_bUTmEsWPzPY1R_ec',
    appId: '1:974894815246:web:6c2c6c88408ccd611bc45f',
    messagingSenderId: '974894815246',
    projectId: 'football-tournament-c0c05',
    authDomain: 'football-tournament-c0c05.firebaseapp.com',
    storageBucket: 'football-tournament-c0c05.firebasestorage.app',
    measurementId: 'G-4GNECVSNWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_mGPEkY0kwR4Z2QoF6epzLQEzUr3Ok2w',
    appId: '1:974894815246:android:c62c1e058aa380211bc45f',
    messagingSenderId: '974894815246',
    projectId: 'football-tournament-c0c05',
    storageBucket: 'football-tournament-c0c05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3IWOeQsTH-j43DfGyBBcIjgxNDk3ZRfY',
    appId: '1:974894815246:ios:82b2b232c92283b21bc45f',
    messagingSenderId: '974894815246',
    projectId: 'football-tournament-c0c05',
    storageBucket: 'football-tournament-c0c05.firebasestorage.app',
    iosBundleId: 'com.example.footballTournament',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3IWOeQsTH-j43DfGyBBcIjgxNDk3ZRfY',
    appId: '1:974894815246:ios:82b2b232c92283b21bc45f',
    messagingSenderId: '974894815246',
    projectId: 'football-tournament-c0c05',
    storageBucket: 'football-tournament-c0c05.firebasestorage.app',
    iosBundleId: 'com.example.footballTournament',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB0Gn3T3lvP2Q-Rn_bUTmEsWPzPY1R_ec',
    appId: '1:974894815246:web:a9aa04903b3f8d161bc45f',
    messagingSenderId: '974894815246',
    projectId: 'football-tournament-c0c05',
    authDomain: 'football-tournament-c0c05.firebaseapp.com',
    storageBucket: 'football-tournament-c0c05.firebasestorage.app',
    measurementId: 'G-RT715LYQ85',
  );
}
